### ISSUE TITLE
Got stuck on  "push origin hw"

### ISSUE THREAD

**Issue by irinafedorovacisc** [cisc3130/docs#5]
I previously configured git with 

$ git config --global user.name "my_github_user_name"
$ git config --global user.email "my_email"
but keep getting permission denied,  what could be a problem?

$ git push origin hw
remote: Permission to cisc3130/0-get-started.git denied to irinafedorovacisc.
fatal: unable to access 'https://github.com/cisc3130/0-get-started.git/': The requested URL returned error: 403

**Comment by DullStudent** [comment]
did you make a branch repository using the command line
$ git checkout -b hw

that might be the problem since you are supposed to have your own branch named hw and this makes it so that when you push it goes into a different branch of the master repository.

you may want to make sure to check your cap size or spacing? when using git or any other terminal make sure to be precise about what you are typing. Ex. File name: helloworld.cpp 
->git add Helloworld.cpp (This are not same as the File name).
Please explain more on your problem if these answers doesnt help.
Also a screenshot can help if you can take one.

**Comment by h01m3s** [comment]
You are not suppose to git clone from https://github.com/cisc3410/0-get-started.git
You should clone from the repository that homework generate for your homework.

For example, I clone from https://github.com/cisc3410/0-get-started-h01m3s

In the https://github.com/cisc3410/0-get-started.git, you might not have permission to do a push.

**Comment by DullStudent** [comment]
right sorry should have stated that a bit more clearly, but h01m3s is right, git clone your personal repository rather than https://github.com/cisc3410/0-get-started.git.
